"""This code will function as a budgeting tool"""

# imports

from datetime import datetime

import json

import csv

# constants

CATEGORIES = [
    "Housing",
    "Food",
    "Transportation",
    "Utilities",
    "Entertainment",
    "Credit Card",
    "Loans",
    "Other"
]

# function definitions


def format_money(amount):
    """
    :param amount: Amount to be formatted in standard accounting style
    """
    if amount < 0:
        return f"(${abs(amount):,.2f})"
    return f"${amount:,.2f}"


def choose_category():
    """
    Display of CATEGORIES for expenses
    """
    print("\nCategories:")
    for index, category in enumerate(CATEGORIES, start=1):
        print(f"{index}. {category}")

    while True:
        category_choice = input("Choose a category number: ")

        if not category_choice.isdigit():
            print("Please enter a number.")
            continue

        index = int(category_choice) - 1

        if 0 <= index < len(CATEGORIES):
            return CATEGORIES[index]

        print("Invalid category number.")


def get_positive_float(prompt):
    """
    General-purpose helper for validating numeric inputs
        :param prompt: Input from User
    """
    while True:
        user_input = input(prompt)

        try:
            value = float(user_input)
        except ValueError:
            print("Please enter a number.")
            continue

        if value < 0:
            print("Value must be zero or greater.")
            continue

        return value


def set_monthly_income(income_by_month):
    """
    :return: Income inputted by user
    """
    try:
        year = int(input("Enter year (YYYY): "))
        month = int(input("Enter month (1-12): "))

        if month < 1 or month > 12:
            print("Month must be between 1 and 12.")
            return

        month_key = f"{year}-{month:02d}"

        amount = get_positive_float("Enter income amount: ")

        income_by_month[month_key] = amount

        print(f"Income set for {month_key}: {format_money(amount)}")

    except ValueError:
        print("Invalid year or month.")


def create_expense(label, amount, category, date):
    """
    Creates an expense dictionary.
    """
    return {
        "label": label,
        "amount": amount,
        "category": category,
        "date": date
    }


def add_expense(expense_items):
    """
    :param expense_items: List of Expenses inputted by user
    """

    label = input("Expense name: ").strip()

    if not label:
        print("Expense name cannot be empty.")
        return

    amount = get_positive_float("Amount: ")

    category = choose_category()

    date = datetime.now().strftime("%Y-%m-%d")

    expense = create_expense(label, amount, category, date)

    expense_items.append(expense)

    print("Expense added.")


def calculate_category_totals(expenses):
    """
    Returns total expenses per category.
    """

    totals = {}

    for expense in expenses:
        category = expense["category"]
        amount = expense["amount"]

        totals[category] = totals.get(category, 0) + amount

    return totals


def print_expenses_by_category(expense_items):
    """
    Displays expenses per category.
    """

    if not expense_items:
        print("\nNo expenses recorded.")
        return

    category_totals = calculate_category_totals(expense_items)

    print("\nExpenses by category:")

    max_category_length = max(len(category) for category in category_totals)

    formatted_values = [format_money(total)
                        for total in category_totals.values()]
    max_value_length = max(len(value) for value in formatted_values)

    for (category, total), formatted in zip(category_totals.items(), formatted_values):
        print(f"{category:<{max_category_length}} : {formatted:>{max_value_length}}")

    top_category = max(category_totals, key=category_totals.get)
    top_amount = category_totals[top_category]

    print(
        f"\nTop spending category: {top_category} ({format_money(top_amount)})")


def list_expenses(expense_items, sort_by=None, reverse=False):
    """
    :param expense_items: Listing expenses generated by the user
    :param sort_by: optional field to sort by ("date" or "amount")
    :param reverse: whether to reverse sort order
    """
    if not expense_items:
        print("\nNo expenses recorded.")
        return

    expenses_to_display = expense_items.copy()

    if sort_by in ("date", "amount"):
        expenses_to_display.sort(
            key=lambda expense: expense.get(sort_by),
            reverse=reverse
        )

    print()

    for index, expense in enumerate(expenses_to_display, start=1):
        print(
            f"{index}. "
            f"{expense.get('date', 'N/A')} | "
            f"{expense['label']} | "
            f"{expense['category']} | "
            f"{format_money(expense['amount'])}"
        )


def prompt_expense_selection(expense_items, action):
    """
    :param expense_items: Listing expenses generated by the user
    :param action: Index of expense to be used
    """
    if not expense_items:
        print(f"No expenses to {action}.")
        return None

    list_expenses(expense_items)

    while True:
        user_input = input(
            f"Choose an expense number to {action} (or 0 to cancel): ")

        if not user_input.isdigit():
            print("Please enter a number.")
            continue

        index = int(user_input)

        if index == 0:
            return None

        if 1 <= index <= len(expense_items):
            return index - 1

        print("Invalid expense number.")


def delete_expense(expense_items):
    """
    :param expense_items: Listing expenses generated by the user
    """
    expense_index = prompt_expense_selection(expense_items, "delete")

    if expense_index is None:
        return

    removed = expense_items.pop(expense_index)
    print(f"Deleted expense: {removed['label']}")


def apply_expense_changes(expense, label=None, amount=None, category=None, date=None):
    """
    Applies updated fields to an expense if new values are provided.
    """

    if label is not None:
        expense["label"] = label

    if amount is not None:
        expense["amount"] = amount

    if category is not None:
        expense["category"] = category

    if date is not None:
        expense["date"] = date


def prompt_edit_expense(expense_items):
    """
    :param expense_items: Listing expenses generated by the user
    """

    expense_index = prompt_expense_selection(expense_items, "edit")

    if expense_index is None:
        return

    expense = expense_items[expense_index]

    print("\nEditing expense (press Enter to keep current value)")

    new_label = input(f"Name [{expense['label']}]: ").strip()
    label = new_label if new_label else None

    new_amount = input(f"Amount [{expense['amount']}]: ").strip()
    amount = None

    if new_amount:
        try:
            value = float(new_amount)
            if value >= 0:
                amount = value
            else:
                print("Amount must be non-negative. Keeping original.")
        except ValueError:
            print("Invalid number. Keeping original.")

    category = None
    change_category = input("Change category? (y/n): ").lower()

    if change_category == "y":
        category = choose_category()

    new_date = input(
        f"Date [{expense.get('date', 'N/A')} - YYYY-MM-DD]: "
    ).strip()

    date = None

    if new_date:
        try:
            parsed_date = datetime.strptime(new_date, "%Y-%m-%d")
            date = parsed_date.strftime("%Y-%m-%d")
        except ValueError:
            print("Invalid date format. Keeping original.")

    apply_expense_changes(expense, label, amount, category, date)

    print("Expense updated.")


def filter_expenses_by_month(expenses, year, month):
    """
    Returns a list of expenses for a given year and month.
    Month should be an integer (1-12).
    """

    month_str = f"{year}-{month:02d}"

    return [
        expense for expense in expenses
        if expense.get("date", "").startswith(month_str)
    ]


def prompt_month_filter(expenses):
    """
    Filtering expenses by user selected year-month
    """
    try:
        year = int(input("Enter year (YYYY): "))
        month = int(input("Enter month (1-12): "))

        filtered = filter_expenses_by_month(expenses, year, month)

        print(f"\nExpenses for {year}-{month:02d}")
        list_expenses(filtered, sort_by="date")

    except ValueError:
        print("Invalid year or month.")


def print_monthly_expense_summary(expenses, year, month):
    """
    Displays an expense-only summary for a given month.
    """

    filtered = filter_expenses_by_month(expenses, year, month)

    if not filtered:
        print(f"\nNo expenses found for {year}-{month:02d}")
        return

    total_expenses = sum(e["amount"] for e in filtered)

    print(f"\nSummary for {year}-{month:02d}")
    print(f"Total Expenses: {format_money(total_expenses)}")

    category_totals = calculate_category_totals(filtered)

    print("\nBy Category:")

    for category, amount in category_totals.items():
        print(f"{category:<15} : {format_money(amount)}")


def prompt_monthly_expense_summary(expenses):
    """
    Prompts user for a month and displays the monthly expense summary.
    """
    try:
        year = int(input("Enter year (YYYY): "))
        month = int(input("Enter month (1-12): "))

        if month < 1 or month > 12:
            print("Month must be between 1 and 12.")
            return

        print_monthly_expense_summary(expenses, year, month)

    except ValueError:
        print("Invalid year or month.")


def calculate_monthly_summary(income_by_month, expenses, year, month):
    """
    Calculates income, expenses and balance for a specific month.
    """

    month_key = f"{year}-{month:02d}"

    income = income_by_month.get(month_key, 0.0)

    monthly_expenses = filter_expenses_by_month(expenses, year, month)

    total_expenses = sum(e["amount"] for e in monthly_expenses)

    balance = income - total_expenses

    return {
        "income": income,
        "expenses": total_expenses,
        "balance": balance
    }


def print_monthly_financial_report(income_by_month, expenses):
    """
    Displays a full financial report (income, expenses, balance) for a specific month.
    """

    try:
        year = int(input("Enter year (YYYY): "))
        month = int(input("Enter month (1-12): "))

        if month < 1 or month > 12:
            print("Month must be between 1 and 12.")
            return

    except ValueError:
        print("Invalid year or month.")
        return

    summary = calculate_monthly_summary(
        income_by_month,
        expenses,
        year,
        month
    )

    print(f"\nFinancial Summary for {year}-{month:02d}")

    report = {
        "Income": summary["income"],
        "Expenses": summary["expenses"],
        "Balance": summary["balance"]
    }

    max_label_length = max(len(label) for label in report)
    formatted_values = [format_money(value) for value in report.values()]
    max_value_length = max(len(value) for value in formatted_values)

    for (label, value), formatted in zip(report.items(), formatted_values):
        print(f"{label:<{max_label_length}} : {formatted:>{max_value_length}}")

    monthly_expenses = filter_expenses_by_month(expenses, year, month)

    print_expenses_by_category(monthly_expenses)


def save_data(income_by_month, expenses, filename="budget.json"):
    """
    :param income_by_month: Monthly income data being saved to file
    :param expenses: Expenses being saved to file
    :param filename: Json file being created
    """
    budget_data = {
        "income_by_month": income_by_month,
        "expenses": expenses
    }

    try:
        with open(filename, "w", encoding="utf-8") as file:
            json.dump(budget_data, file, indent=4)
        print("Data saved successfully.")
    except OSError as error:
        print(f"Error saving data: {error}")


def load_data(filename="budget.json"):
    """
    :param filename: Json file being read
    """
    try:
        with open(filename, "r", encoding="utf-8") as file:
            loaded_data = json.load(file)

        income_by_month = loaded_data.get("income_by_month", {})
        expenses = loaded_data.get("expenses", [])

        print("Data loaded successfully.")
        return income_by_month, expenses

    except FileNotFoundError:
        print("No saved data found. Starting fresh.")
        return {}, []

    except (json.JSONDecodeError, OSError) as error:
        print(f"Error loading data: {error}")
        return {}, []


def export_to_csv(expenses, filename="expenses_report.csv"):
    """
    Exporting list of Expenses to CSV file
    """
    if not expenses:
        print("\nNo expenses to export.")
        return

    with open(filename, "w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)

        writer.writerow(["Date", "Label", "Category", "Amount"])

        for expense in expenses:
            writer.writerow([
                expense["date"],
                expense["label"],
                expense["category"],
                expense["amount"]
            ])

    print(f"\nExpenses exported successfully to {filename}")


def calculate_overall_summary(income_by_month, expenses):
    """
    Calculates totals for the overall financial summary across all months.
    """

    total_income = sum(income_by_month.values())
    total_expenses = sum(e["amount"] for e in expenses)
    balance = total_income - total_expenses

    return {
        "Total Income": total_income,
        "Total Expenses": total_expenses,
        "Overall Balance": balance
    }


def show_summary(income_by_month, expenses):
    """
    Displays overall financial summary across all months.
    """

    print("\nSummary")

    summary = calculate_overall_summary(income_by_month, expenses)

    max_label_length = max(len(label) for label in summary)
    formatted_values = [format_money(value) for value in summary.values()]
    max_value_length = max(len(value) for value in formatted_values)

    for (label, value), formatted in zip(summary.items(), formatted_values):
        print(f"{label:<{max_label_length}} : {formatted:>{max_value_length}}")

    print_expenses_by_category(expenses)


def get_menu_choice():
    """
    Helper to validate correct input in Menu
    """
    valid_choices = {"1", "2", "3", "4", "5",
                     "6", "7", "8", "9", "10", "11", "12"}

    while True:
        menu_choice = input("Choose an option: ")

        if menu_choice in valid_choices:
            return menu_choice

        print("Invalid option. Please choose 1–12.")


def show_menu():
    """Initial Menu setup"""

    print("\nMenu")
    print("1. Set income")
    print("2. Add expense")
    print("3. Show overall summary")
    print("4. Edit expense")
    print("5. Delete expense")
    print("6. Save data")
    print("7. Load data")
    print("8. Export to CSV")
    print("9. Filter by month")
    print("10. Monthly Expense Summary")
    print("11. Monthly Financial Summary")
    print("12. Exit")


def main():
    """
    Running the program and holding runtime state.
    """

    income_by_month = {}
    expenses = []

    while True:
        show_menu()
        user_choice = get_menu_choice()

        if user_choice == "1":
            set_monthly_income(income_by_month)

        elif user_choice == "2":
            add_expense(expenses)

        elif user_choice == "3":
            show_summary(income_by_month, expenses)

        elif user_choice == "4":
            prompt_edit_expense(expenses)

        elif user_choice == "5":
            delete_expense(expenses)

        elif user_choice == "6":
            save_data(income_by_month, expenses)

        elif user_choice == "7":
            income_by_month, expenses = load_data()

        elif user_choice == "8":
            export_to_csv(expenses)

        elif user_choice == "9":
            prompt_month_filter(expenses)

        elif user_choice == "10":
            prompt_monthly_expense_summary(expenses)

        elif user_choice == "11":
            print_monthly_financial_report(income_by_month, expenses)

        elif user_choice == "12":
            print("Goodbye!")
            break


if __name__ == "__main__":
    main()
